/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainingIndexRouteImport } from './routes/training/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as FaqsIndexRouteImport } from './routes/faqs/index'
import { Route as ArticlesIndexRouteImport } from './routes/articles/index'
import { Route as TrainingIdRouteImport } from './routes/training/$id'
import { Route as ServicesSlugRouteImport } from './routes/services/$slug'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalMentionsRouteImport } from './routes/legal/mentions'
import { Route as LegalCgvRouteImport } from './routes/legal/cgv'
import { Route as ArticlesSlugRouteImport } from './routes/articles/$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingIndexRoute = TrainingIndexRouteImport.update({
  id: '/training/',
  path: '/training/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsIndexRoute = FaqsIndexRouteImport.update({
  id: '/faqs/',
  path: '/faqs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingIdRoute = TrainingIdRouteImport.update({
  id: '/training/$id',
  path: '/training/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalMentionsRoute = LegalMentionsRouteImport.update({
  id: '/legal/mentions',
  path: '/legal/mentions',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCgvRoute = LegalCgvRouteImport.update({
  id: '/legal/cgv',
  path: '/legal/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/legal/cgv': typeof LegalCgvRoute
  '/legal/mentions': typeof LegalMentionsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/training/$id': typeof TrainingIdRoute
  '/articles/': typeof ArticlesIndexRoute
  '/faqs/': typeof FaqsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/training/': typeof TrainingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/legal/cgv': typeof LegalCgvRoute
  '/legal/mentions': typeof LegalMentionsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/training/$id': typeof TrainingIdRoute
  '/articles': typeof ArticlesIndexRoute
  '/faqs': typeof FaqsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/training': typeof TrainingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/legal/cgv': typeof LegalCgvRoute
  '/legal/mentions': typeof LegalMentionsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/training/$id': typeof TrainingIdRoute
  '/articles/': typeof ArticlesIndexRoute
  '/faqs/': typeof FaqsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/training/': typeof TrainingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects'
    | '/search'
    | '/sitemap.xml'
    | '/articles/$slug'
    | '/legal/cgv'
    | '/legal/mentions'
    | '/legal/privacy'
    | '/services/$slug'
    | '/training/$id'
    | '/articles/'
    | '/faqs/'
    | '/services/'
    | '/training/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects'
    | '/search'
    | '/sitemap.xml'
    | '/articles/$slug'
    | '/legal/cgv'
    | '/legal/mentions'
    | '/legal/privacy'
    | '/services/$slug'
    | '/training/$id'
    | '/articles'
    | '/faqs'
    | '/services'
    | '/training'
  id:
    | '__root__'
    | '/'
    | '/projects'
    | '/search'
    | '/sitemap.xml'
    | '/articles/$slug'
    | '/legal/cgv'
    | '/legal/mentions'
    | '/legal/privacy'
    | '/services/$slug'
    | '/training/$id'
    | '/articles/'
    | '/faqs/'
    | '/services/'
    | '/training/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsRoute: typeof ProjectsRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  LegalCgvRoute: typeof LegalCgvRoute
  LegalMentionsRoute: typeof LegalMentionsRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  TrainingIdRoute: typeof TrainingIdRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  FaqsIndexRoute: typeof FaqsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  TrainingIndexRoute: typeof TrainingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/': {
      id: '/training/'
      path: '/training'
      fullPath: '/training/'
      preLoaderRoute: typeof TrainingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs/': {
      id: '/faqs/'
      path: '/faqs'
      fullPath: '/faqs/'
      preLoaderRoute: typeof FaqsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/$id': {
      id: '/training/$id'
      path: '/training/$id'
      fullPath: '/training/$id'
      preLoaderRoute: typeof TrainingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/mentions': {
      id: '/legal/mentions'
      path: '/legal/mentions'
      fullPath: '/legal/mentions'
      preLoaderRoute: typeof LegalMentionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cgv': {
      id: '/legal/cgv'
      path: '/legal/cgv'
      fullPath: '/legal/cgv'
      preLoaderRoute: typeof LegalCgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsRoute: ProjectsRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  LegalCgvRoute: LegalCgvRoute,
  LegalMentionsRoute: LegalMentionsRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  TrainingIdRoute: TrainingIdRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  FaqsIndexRoute: FaqsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  TrainingIndexRoute: TrainingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
