/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AppointmentRouteImport } from './routes/appointment'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainingIndexRouteImport } from './routes/training/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as TestsIndexRouteImport } from './routes/tests/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as FaqsIndexRouteImport } from './routes/faqs/index'
import { Route as ArticlesIndexRouteImport } from './routes/articles/index'
import { Route as TrainingIdRouteImport } from './routes/training/$id'
import { Route as ToolsLookupRouteImport } from './routes/tools/lookup'
import { Route as ToolsAppointmentRouteImport } from './routes/tools/appointment'
import { Route as TestsRessourcesRouteImport } from './routes/tests/ressources'
import { Route as TestsNewsletterRouteImport } from './routes/tests/newsletter'
import { Route as TestsDevisRouteImport } from './routes/tests/devis'
import { Route as TestsCalendarRouteImport } from './routes/tests/calendar'
import { Route as TestsAffiliationRouteImport } from './routes/tests/affiliation'
import { Route as ServicesSlugRouteImport } from './routes/services/$slug'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalMentionsRouteImport } from './routes/legal/mentions'
import { Route as LegalCgvRouteImport } from './routes/legal/cgv'
import { Route as ArticlesSlugRouteImport } from './routes/articles/$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentRoute = AppointmentRouteImport.update({
  id: '/appointment',
  path: '/appointment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingIndexRoute = TrainingIndexRouteImport.update({
  id: '/training/',
  path: '/training/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsIndexRoute = TestsIndexRouteImport.update({
  id: '/tests/',
  path: '/tests/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsIndexRoute = FaqsIndexRouteImport.update({
  id: '/faqs/',
  path: '/faqs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingIdRoute = TrainingIdRouteImport.update({
  id: '/training/$id',
  path: '/training/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsLookupRoute = ToolsLookupRouteImport.update({
  id: '/tools/lookup',
  path: '/tools/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsAppointmentRoute = ToolsAppointmentRouteImport.update({
  id: '/tools/appointment',
  path: '/tools/appointment',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsRessourcesRoute = TestsRessourcesRouteImport.update({
  id: '/tests/ressources',
  path: '/tests/ressources',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsNewsletterRoute = TestsNewsletterRouteImport.update({
  id: '/tests/newsletter',
  path: '/tests/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsDevisRoute = TestsDevisRouteImport.update({
  id: '/tests/devis',
  path: '/tests/devis',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsCalendarRoute = TestsCalendarRouteImport.update({
  id: '/tests/calendar',
  path: '/tests/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsAffiliationRoute = TestsAffiliationRouteImport.update({
  id: '/tests/affiliation',
  path: '/tests/affiliation',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalMentionsRoute = LegalMentionsRouteImport.update({
  id: '/legal/mentions',
  path: '/legal/mentions',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCgvRoute = LegalCgvRouteImport.update({
  id: '/legal/cgv',
  path: '/legal/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointment': typeof AppointmentRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/legal/cgv': typeof LegalCgvRoute
  '/legal/mentions': typeof LegalMentionsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/tests/affiliation': typeof TestsAffiliationRoute
  '/tests/calendar': typeof TestsCalendarRoute
  '/tests/devis': typeof TestsDevisRoute
  '/tests/newsletter': typeof TestsNewsletterRoute
  '/tests/ressources': typeof TestsRessourcesRoute
  '/tools/appointment': typeof ToolsAppointmentRoute
  '/tools/lookup': typeof ToolsLookupRoute
  '/training/$id': typeof TrainingIdRoute
  '/articles/': typeof ArticlesIndexRoute
  '/faqs/': typeof FaqsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/tests/': typeof TestsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/training/': typeof TrainingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointment': typeof AppointmentRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/legal/cgv': typeof LegalCgvRoute
  '/legal/mentions': typeof LegalMentionsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/tests/affiliation': typeof TestsAffiliationRoute
  '/tests/calendar': typeof TestsCalendarRoute
  '/tests/devis': typeof TestsDevisRoute
  '/tests/newsletter': typeof TestsNewsletterRoute
  '/tests/ressources': typeof TestsRessourcesRoute
  '/tools/appointment': typeof ToolsAppointmentRoute
  '/tools/lookup': typeof ToolsLookupRoute
  '/training/$id': typeof TrainingIdRoute
  '/articles': typeof ArticlesIndexRoute
  '/faqs': typeof FaqsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/tests': typeof TestsIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/training': typeof TrainingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointment': typeof AppointmentRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/legal/cgv': typeof LegalCgvRoute
  '/legal/mentions': typeof LegalMentionsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/tests/affiliation': typeof TestsAffiliationRoute
  '/tests/calendar': typeof TestsCalendarRoute
  '/tests/devis': typeof TestsDevisRoute
  '/tests/newsletter': typeof TestsNewsletterRoute
  '/tests/ressources': typeof TestsRessourcesRoute
  '/tools/appointment': typeof ToolsAppointmentRoute
  '/tools/lookup': typeof ToolsLookupRoute
  '/training/$id': typeof TrainingIdRoute
  '/articles/': typeof ArticlesIndexRoute
  '/faqs/': typeof FaqsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/tests/': typeof TestsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/training/': typeof TrainingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointment'
    | '/search'
    | '/sitemap.xml'
    | '/articles/$slug'
    | '/legal/cgv'
    | '/legal/mentions'
    | '/legal/privacy'
    | '/services/$slug'
    | '/tests/affiliation'
    | '/tests/calendar'
    | '/tests/devis'
    | '/tests/newsletter'
    | '/tests/ressources'
    | '/tools/appointment'
    | '/tools/lookup'
    | '/training/$id'
    | '/articles/'
    | '/faqs/'
    | '/projects/'
    | '/services/'
    | '/tests/'
    | '/tools/'
    | '/training/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointment'
    | '/search'
    | '/sitemap.xml'
    | '/articles/$slug'
    | '/legal/cgv'
    | '/legal/mentions'
    | '/legal/privacy'
    | '/services/$slug'
    | '/tests/affiliation'
    | '/tests/calendar'
    | '/tests/devis'
    | '/tests/newsletter'
    | '/tests/ressources'
    | '/tools/appointment'
    | '/tools/lookup'
    | '/training/$id'
    | '/articles'
    | '/faqs'
    | '/projects'
    | '/services'
    | '/tests'
    | '/tools'
    | '/training'
  id:
    | '__root__'
    | '/'
    | '/appointment'
    | '/search'
    | '/sitemap.xml'
    | '/articles/$slug'
    | '/legal/cgv'
    | '/legal/mentions'
    | '/legal/privacy'
    | '/services/$slug'
    | '/tests/affiliation'
    | '/tests/calendar'
    | '/tests/devis'
    | '/tests/newsletter'
    | '/tests/ressources'
    | '/tools/appointment'
    | '/tools/lookup'
    | '/training/$id'
    | '/articles/'
    | '/faqs/'
    | '/projects/'
    | '/services/'
    | '/tests/'
    | '/tools/'
    | '/training/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentRoute: typeof AppointmentRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  LegalCgvRoute: typeof LegalCgvRoute
  LegalMentionsRoute: typeof LegalMentionsRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  TestsAffiliationRoute: typeof TestsAffiliationRoute
  TestsCalendarRoute: typeof TestsCalendarRoute
  TestsDevisRoute: typeof TestsDevisRoute
  TestsNewsletterRoute: typeof TestsNewsletterRoute
  TestsRessourcesRoute: typeof TestsRessourcesRoute
  ToolsAppointmentRoute: typeof ToolsAppointmentRoute
  ToolsLookupRoute: typeof ToolsLookupRoute
  TrainingIdRoute: typeof TrainingIdRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  FaqsIndexRoute: typeof FaqsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  TestsIndexRoute: typeof TestsIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  TrainingIndexRoute: typeof TrainingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointment': {
      id: '/appointment'
      path: '/appointment'
      fullPath: '/appointment'
      preLoaderRoute: typeof AppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/': {
      id: '/training/'
      path: '/training'
      fullPath: '/training/'
      preLoaderRoute: typeof TrainingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/': {
      id: '/tests/'
      path: '/tests'
      fullPath: '/tests/'
      preLoaderRoute: typeof TestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs/': {
      id: '/faqs/'
      path: '/faqs'
      fullPath: '/faqs/'
      preLoaderRoute: typeof FaqsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/$id': {
      id: '/training/$id'
      path: '/training/$id'
      fullPath: '/training/$id'
      preLoaderRoute: typeof TrainingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/lookup': {
      id: '/tools/lookup'
      path: '/tools/lookup'
      fullPath: '/tools/lookup'
      preLoaderRoute: typeof ToolsLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/appointment': {
      id: '/tools/appointment'
      path: '/tools/appointment'
      fullPath: '/tools/appointment'
      preLoaderRoute: typeof ToolsAppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/ressources': {
      id: '/tests/ressources'
      path: '/tests/ressources'
      fullPath: '/tests/ressources'
      preLoaderRoute: typeof TestsRessourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/newsletter': {
      id: '/tests/newsletter'
      path: '/tests/newsletter'
      fullPath: '/tests/newsletter'
      preLoaderRoute: typeof TestsNewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/devis': {
      id: '/tests/devis'
      path: '/tests/devis'
      fullPath: '/tests/devis'
      preLoaderRoute: typeof TestsDevisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/calendar': {
      id: '/tests/calendar'
      path: '/tests/calendar'
      fullPath: '/tests/calendar'
      preLoaderRoute: typeof TestsCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/affiliation': {
      id: '/tests/affiliation'
      path: '/tests/affiliation'
      fullPath: '/tests/affiliation'
      preLoaderRoute: typeof TestsAffiliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/mentions': {
      id: '/legal/mentions'
      path: '/legal/mentions'
      fullPath: '/legal/mentions'
      preLoaderRoute: typeof LegalMentionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cgv': {
      id: '/legal/cgv'
      path: '/legal/cgv'
      fullPath: '/legal/cgv'
      preLoaderRoute: typeof LegalCgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentRoute: AppointmentRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  LegalCgvRoute: LegalCgvRoute,
  LegalMentionsRoute: LegalMentionsRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  TestsAffiliationRoute: TestsAffiliationRoute,
  TestsCalendarRoute: TestsCalendarRoute,
  TestsDevisRoute: TestsDevisRoute,
  TestsNewsletterRoute: TestsNewsletterRoute,
  TestsRessourcesRoute: TestsRessourcesRoute,
  ToolsAppointmentRoute: ToolsAppointmentRoute,
  ToolsLookupRoute: ToolsLookupRoute,
  TrainingIdRoute: TrainingIdRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  FaqsIndexRoute: FaqsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  TestsIndexRoute: TestsIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  TrainingIndexRoute: TrainingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
